# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c95ac14cff73ddbd55ec993ab5ab7faea731a001d3935808455c623400480131665525a0012f9544164321cf9aa914a8bfe4d37622363175868b4221d6ecbf28

test:
  secret_key_base: ee6bd9b4765627b5f0e70adddc8e8d8ea88eca2854c7db075b333dad94a33fa105fc540d1080b40cda78c55f62dccc1f5834593ce26f4b8a93e316331e5f14bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
